---

admin_email: lmaguina@pucp.pe

plone_initial_password: admin

# muninnode_query_ips:
#     - "159.203.252.51"

# If you do not have a Munin monitor running, comment out the
# muninnode_query_ips and uncomment the line below:

install_muninnode: no

timezone: "America/Los_Angeles"

additional_packages:
  - sockstat
  - screen
  - ntp
  - ack-grep

mailserver_maincf_extras: |
  inet_protocols = ipv4

# Major settings
# --------------

# Plone 4.3.x and 5.0.x are currently tested and working.
# Make sure this setting is quoted so that it's interpreted as a string.
plone_version: '4.3.15'

# With one core, we don't need multiple zeo clients
plone_client_count: 1

# instead, we'll run two Zope threads
plone_zserver_threads: 2

# with only one zeo client, we don't need a load balancer
install_loadbalancer: no

# since we're not using a load balancer, tell Varnish to look at client1.
loadbalancer_port: 8081

# Colonialart objects are huge; we need a much smaller than usual ZODB cache size.
plone_zodb_cache_size: 1000

# and enforce that with a memory-monitor
plone_client_max_memory: 1200MB
plone_hot_monitor: cron


# We'll use varnish, but since we're memory-limited, with a
# file-based cache.
proxycache_method: file

plone_additional_eggs:
  - wildcard.foldercontents
  - Products.LinguaPlone
  - collective.correspondences
  - diazotheme.colonialart
plone_sources:
  - "collective.correspondences = git https://github.com/smcmahon/collective.correspondences.git"
  - "diazotheme.colonialart = git https://github.com/smcmahon/diazotheme.colonialart.git"
plone_additional_versions:
  - "Products.LinguaPlone = 4.1.3"
  - "collective.dexteritytextindexer = 2.1.1"
  - "wildcard.foldercontents = 1.3.3"
  - "jarn.jsi18n = 1.1"
  - "z3c.jbot = 0.7.2"
webserver_virtualhosts:
  - hostname: colonialart.org
    default_server: yes
    zodb_path: /colonialart
    aliases:
      - www.colonialart.org
      - artecolonial.org
      - www.artecolonial.org
    rewrite_server_name: host

